name: Tailscale ACL syncing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  acls:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Fetch old version info
        id: fetch-old-version
        uses: actions/cache@v3
        with:
          path: .
          key: version-cache.json

      - name: Deploy ACL
        if: github.event_name == 'push'
        id: deploy-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.tskey-api-kCtmfhmSVe11CNTRL-LHCD988sdz43Lou711ef15JHuhbJPF3sW }}
          tailnet: ${{ hmorris1990.github }}
          action: apply

      - name: ACL tests
        if: github.event_name == 'pull_request'
        id: test-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.tskey-api-kCtmfhmSVe11CNTRL-LHCD988sdz43Lou711ef15JHuhbJPF3sW }}
          tailnet: ${{ hmorris1990.github }}
          action: test

